### ISSUE TITLE
Documentation not aligned with codebase

### ISSUE THREAD

**Issue by donfelipee** [rudderlabs/rudder-sdk-python#20]
Hello,

raising this issue to create awareness around the release of version v2.0.1 which is the most recent release on Pypi.

I realized that the current documentation is not alinged with the code in the codebase.  In particular, I struggled with connecting my python BE with the SDK. 

The documentation states, that the data plane URL needs to be connected to the `dataPlaneUrl` property of the client. However, I found that this property is not working as expected. Instead, the current version still accepts the parameter `host`, which according to the code should raise a deprecation warning, which it currently does not do. It would be great to align the documentation with the actual behaviour. Furthermore, I find the mixture between camelCase and snake_case misleading. According to the lastest release the `dataPlaneUrl` should be in camel case, but the other parameters are in snake case.

Examples: 
- https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-python-sdk/ uses snake case
- github documentation uses camelcase
- code does not accept either, but parameter host.

**Comment by itsdebs** [comment]
@donfelipee We are in process of releasing the latest documentation. It will be live within a couple of days.
Meanwhile can you add the code snippet you used to set the dataPlaneUrl and the error you're getting?

**Comment by ilikerobots** [comment]
@donfelipee : thanks for posting the issue and fix, you just saved me a lot of time.

**Comment by itsdebs** [comment]
Fixed in Version 2.0.2
