### ISSUE TITLE
Dependency conflict when trying to use Python SDK

### ISSUE THREAD

**Issue by ranganathkoman** [rudderlabs/rudder-sdk-python#27]
Customer is trying to use the python SDK, but there is a dependency conflict. They are using Supabase so they need the postgrest lib and it relies on `deprecation`.
postgrest 0.11.0 depends on deprecation<3.0.0 and >=2.1.0
rudder-sdk-python 2.0.2 depends on deprecation~=2.0.6

**Comment by itsdebs** [comment]
We will be fixing this on next release

**Comment by itsdebs** [comment]
Fixed in v2.1.0.
